# Generated by Django 6.0.4 on 2026-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://storage.googleapis.com/ds-builder-bucket/000_menu_placeholder.png', max_length=500),
        ),
    ]
